# Electron Builder Configuration Override
# This file provides additional optimization settings

electronDist: node_modules/electron/dist
includeSubNodeModules: false
buildDependenciesFromSource: false

# File patterns to exclude from the build
files:
  - "!**/*.md"
  - "!**/*.map"
  - "!**/.git/**"
  - "!**/.github/**"
  - "!**/.vscode/**"
  - "!**/test/**"
  - "!**/tests/**"
  - "!**/__tests__/**"
  - "!**/spec/**"
  - "!**/docs/**"
  - "!**/example/**"
  - "!**/examples/**"
  - "!**/samples/**"
  - "!**/*.test.js"
  - "!**/*.spec.js"
  - "!**/.DS_Store"
  - "!**/Thumbs.db"
  - "!**/package-lock.json"
  - "!**/yarn.lock"
  - "!**/pnpm-lock.yaml"
  - "!**/*.log"
  - "!**/*.swp"
  - "!**/*.swo"
  - "!**/*~"
  - "!**/.npmrc"
  - "!**/.yarnrc"
  - "!**/.editorconfig"
  - "!**/.gitignore"
  - "!**/.gitattributes"
  - "!**/.prettierrc*"
  - "!**/.eslintrc*"
  - "!**/.babelrc*"
  - "!**/tsconfig.json"
  - "!**/jsconfig.json"
  - "!**/jest.config.*"
  - "!**/rollup.config.*"
  - "!**/webpack.config.*"
  - "!**/Gruntfile.js"
  - "!**/gulpfile.js"
  - "!**/LICENSE*"
  - "!**/CHANGELOG*"
  - "!**/AUTHORS*"
  - "!**/CONTRIBUTORS*"
  - "!**/PATENTS*"
  - "!**/TODO*"
  - "!**/Makefile"
  - "!**/CMakeLists.txt"
  - "!**/*.gyp"
  - "!**/*.gypi"
  - "!**/*.mk"
  - "!**/*.c"
  - "!**/*.cc"
  - "!**/*.cpp"
  - "!**/*.h"
  - "!**/*.hpp"
  - "!**/*.py"
  - "!**/*.pyc"
  - "!**/*.pyo"
  - "!**/*.ts"
  - "!**/*.tsx"
  - "!**/*.coffee"
  - "!**/*.less"
  - "!**/*.sass"
  - "!**/*.scss"
  - "!**/*.styl"
  - "!**/node_modules/**/test/**"
  - "!**/node_modules/**/.bin/**"
  - "!**/node_modules/**/example/**"
  - "!**/node_modules/**/examples/**"
  - "!**/node_modules/**/build/**"
  - "!**/node_modules/**/docs/**"
  - "!**/node_modules/**/*.md"
  - "!**/node_modules/**/*.markdown"
  - "!**/node_modules/**/*.rst"
  - "!**/node_modules/**/*.txt"
  - "!**/node_modules/**/LICENSE*"
  - "!**/node_modules/**/CHANGELOG*"
  - "!**/node_modules/**/History.md"
  - "!**/node_modules/**/.travis.yml"
  - "!**/node_modules/**/.github/**"
  - "!**/node_modules/**/.idea/**"
  - "!**/node_modules/**/.vscode/**"
  - "!**/node_modules/**/.git/**"
  - "!**/node_modules/**/.gitignore"
  - "!**/node_modules/**/.npmignore"
  - "!**/node_modules/**/.editorconfig"
  - "!**/node_modules/**/.eslintrc*"
  - "!**/node_modules/**/.prettierrc*"
  - "!**/node_modules/**/.jshintrc*"
  - "!**/node_modules/**/Makefile"
  - "!**/node_modules/**/Gruntfile.js"
  - "!**/node_modules/**/gulpfile.js"
  - "!**/node_modules/**/karma.conf.js"
  - "!**/node_modules/**/webpack.config.js"
  - "!**/node_modules/**/rollup.config.js"